title: quansight writers workshop
author: quansight
copyright: '2021'
logo: ''
repository: {}
execute:
  execute_notebooks: off
only_build_toc_files: true
exclude_patterns: []
html:
  favico: ''
  use_edit_page_button: false
  use_repository_button: false
  use_issues_button: false
  extra_navbar: ''
  extra_footer: ''
  google_analytics_id: ''
  home_page_in_navbar: true
  baseurl: ''
  comments:
    hypothesis: false
    utterances: false
sphinx:
  extra_extensions: []
  local_extensions: {}
  config: 
    html_baseurl: "https://quansight-writers-workshop.readthedocs.io/en/latest/"
    extra_extensions: 
    - sphinx_sitemap
    nb_render_priority:
      html:
      - "application/vnd.jupyter.widget-view+json"
      - "application/javascript"
      - "text/html"
      - "image/svg+xml"
      - "image/png"
      - "image/jpeg"
      - "text/markdown"
      - "text/latex"
      - "text/plain"